app/api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework.urlpatterns import format_suffix_patterns

from . import viewsets

urlpatterns = patterns('',
   url(r'^$', viewsets.api_root),
   url(r'^clients/$', viewsets.ClientViewSet.as_view({'get': 'list'}), name='client-list'),
   url(r'^groups/$', viewsets.GroupViewSet.as_view({'get': 'list'}), name='group-list')
)

urlpatterns = format_suffix_patterns(urlpatterns)

app/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.conf.urls.i18n import i18n_patterns

import logging


log = logging.getLogger(__name__)

urlpatterns = i18n_patterns('',

  url(r'^admin/', include(admin.site.urls)),
  url(r'^i18n/', include('django.conf.urls.i18n')),
  

  url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
  url(r'^settings/', include('setting.urls', namespace='settings')),
  url(r'^api/', include('api.urls', namespace="api")),
  url(r'^entertainment/', include('entertainment.urls', namespace="entertainment")),
  
  url(r'^$', auth_views.login, {'template_name': 'project/index.html'}, name="login"),
  url(r'password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect' : '/password/reset/done/',
        'template_name': 'registration/password_reset_form.html'},
        name="password_reset"),
  url(r'^password/reset/done/$', auth_views.password_reset_done, name='password_reset_done' ),
  url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect' : '/password/reset/complete/'}, name='password_reset_confirm'),
  url(r'^password/reset/complete/$', auth_views.password_reset_complete),

  )

app/setting/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',

       url(r'^logout/$', views.user_logout,
           name='user_logout'),

       url(r'^general_settings/$', views.GeneralSettingsView.as_view(),
           name='general_settings'),

       url(r'^users/$', views.users_list, name='users_list'),
       #url(r'^users/add/$', views.add_edit_user,
           #name='add_user'),
       url(r'^users/edit/(?P<pk>[0-9]+)/$',
           views.EditUserView.as_view(), name='edit_user'),

       url(r'^groups/$', views.GroupListView.as_view(),
           name='groups_list'),
       url(r'^groups/add/$', views.AddGroupView.as_view(),
           name='add_group'),
       url(r'^groups/edit/(?P<pk>[0-9]+)/$',
           views.EditGroupView.as_view(), name='edit_group'),

       url(r'^moduls/$', views.ModulList.as_view(),
           name='moduls_list'),
       url(r'^moduls/add/$',
           views.ModulCreateView.as_view(), name='add_modul'),
       url(r'^moduls/delete/(?P<modul_id>[0-9]+)/$',
           views.delete_modul, name='delete_modul'),

       url(r'^clients/$', views.ClientListView.as_view(),
           name='clients_list'),
       url(r'^clients/add/$', views.add_edit_client,
           name='add_client'),
       url(r'^clients/edit/(?P<client_id>[0-9]+)/$',
           views.add_edit_client, name='edit_client'),
       url(r'^clients/delete/(?P<client_id>[0-9]+)/$',
           views.ClientDeleteView.as_view(), name='delete_client'),
       url(r'^clients/notification_settings/(?P<client_id>[0-9]+)/$',
           views.edit_client_notification, name='edit_client_notification'),

       url(r'^moduls/activate/(?P<client_id>[0-9]+)/(?P<pin_number>[0-9]+)/(?P<status>[A-Za-z]+)/$',
           views.activate_modul, name='activate_modul'),

       url(r'^events/add/$', views.AddEventView.as_view(),
           name='add_event'),
       url(r'^events/edit/(?P<pk>[0-9]+)/$',
           views.EditEventView.as_view(), name='edit_event'),
       )

app/setting/forms.py
from django.forms import ModelForm, PasswordInput
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

import logging

from models import Group, Client, Modul, Event

log = logging.getLogger(__name__)


class ModulForm(ModelForm):
    """
    Form which is used to work with Modul informations
    """

    class Meta:
        model = Modul
        fields = [
            'name', 'description', 'is_general',
            'pin_number', 'is_input', 'client',
            'is_activated'
        ]


class ClientForm(ModelForm):
    """
    Form which is used to add/edit some client
    """

    class Meta:
        model = Client
        fields = [
            'name', 'description', 'ip_address',
            'port', 'group'
        ]

class GroupForm(ModelForm):
    """
    Form is used to add/edit some Group
    """
    class Meta:
        model = Group
        fields = [
            'name', 'description'
        ]

class EventForm(ModelForm):
    """
    TODO
    """
    class Meta:
        model = Event
        fields = [
            'name', 'start_time',
            'is_periodically', 'end_time'
        ]


class UserForm(ModelForm):
    """
    Form is used to edit/update own user profile, or edit other user
    info
    """
    password = forms.CharField(
        required=False,
        max_length=50,
        widget=PasswordInput
        )
    confirm_password = forms.CharField(
        required=False,
        max_length=50,
        widget=PasswordInput
        )

    class Meta:
        model = User
        fields = [
            'username', 'first_name', 'last_name',
            'email'
        ]
    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        #self.fields['username'].widget.attrs['disabled'] = True

    def clean(self):
        msg = {
            'not_equals': 'Sorry, passwords do not match.',
            'no_password': "Please fill in new password",
            'no_confirm_password': "Please confirm your new password"
        }
        cleaned_data = super(UserForm, self).clean()
        new_password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if new_password and not confirm_password:
            self.add_error('password', _(msg['no_confirm_password']))
        if not new_password and confirm_password:
            self.add_error('password', _(msg['no_password']))
        if new_password != confirm_password:
            self.add_error('password', _(msg['not_equals']))

app/setting/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext as _
from django.views.generic import ListView, CreateView, View, UpdateView
from django.views.generic.edit import FormView
from django.utils import timezone as tz
from django.core.exceptions import ObjectDoesNotExist

import logging
import requests
import json
from dateutil.parser import parse
from celery.result import AsyncResult

import project.settings as settings
from forms import ClientForm, ModulForm, EventForm, UserForm, GroupForm
from models import Client, Event, EventActivationElements, Group, Modul
from .tasks import handle_event
from core.utils import codes
from utils import all_online_moduls


log = logging.getLogger(__name__)


class GeneralSettingsView(View):
    """
    TODO
    """
    template_name = 'settings/general_settings.html'

    def get(self, request, *args, **kwargs):
        return TemplateResponse( request, self.template_name)


def user_logout(request):
    """
    This method is used to logout currently logged user
    :param request: Request, which hold information about user
    :type request: Request object
    :return: HttpRsponseRedirect to login page
    """
    logout(request)
    return HttpResponseRedirect("/")


@login_required
def users_list(request):
    """
    This method is in use to get all active users.
    """
    template_name = 'settings/users/users_list.html'
    users = User.objects.all().filter(is_active=True)
    return TemplateResponse(request, template_name, {
        'users': users,
    })


class EditUserView(UpdateView):
    """
    TODO
    """
    model = User
    form_class = UserForm
    template_name = "settings/users/add_edit_user.html"
    success_url = "/dashboard/"


class GroupListView(ListView):
    """
    TODO
    """
    model = Group
    template_name = 'settings/groups/groups.html'
    context_object_name = 'groups'


class AddGroupView(FormView, CreateView):
    """
    TODO
    """
    form_class = GroupForm
    template_name = "settings/groups/add_edit_group.html"
    success_url = "/settings/groups/"


class EditGroupView(UpdateView):
    """
    TODO
    """
    model = Group
    fields = ['name', 'description']
    template_name = "settings/groups/add_edit_group.html"
    success_url = "/settings/groups/"

    def get_context_data(self, **kwargs):
        context = super(EditGroupView, self).get_context_data(**kwargs)
        context['group_id'] = self.kwargs['pk']
        clients = Client.objects.filter(group_id=self.kwargs['pk'])
        moduls = Modul.objects.filter(group_id = self.kwargs['pk'])
        from itertools import chain
        childs = list(chain(clients, moduls))

        context['childs'] = childs
        return context

class ClientListView(ListView):
    """
    TODO
    """
    model = Client
    template_name = 'settings/clients/clients.html'
    context_object_name = 'clients'


@login_required
def add_edit_client(request, client_id=None):
    """
    Method is used to create or edit some existing client. When new client is created
    notification email is sended on current logged user email.
    :param client_id: ID of the client, which is edited
    :type client_id: Integer
    """
    template_name = 'settings/clients/add_edit_client.html' 
    from_email = settings.EMAIL_HOST
    to_email = request.user.email
    text = {
            'created_email_body': _("New client has been successfully created on {0}. To authorize it \
                                         use this generated key {1} ."),
            'created_email_subject': _("New client has been successfully created"),
            'created': _("Client '{0}' with id={1} has been created"),
            'created_log': _("Email after creation sended for client '{0}' with id={1}"),
            'created_success': _('Additional info were sended on email'),
            'edited': "Client '{0}' with id={1} has been edited"
    }

    if client_id:
        client = get_object_or_404(Client, pk=client_id)
    else:
        client = Client()
        client.key = get_random_string(length=32)

    if request.POST:
        client_form = ClientForm(request.POST, instance=client)
        if client_form.is_valid():
            client_form.save()
            if not client_id:
                log.info(text['created'].format(client.name, client.id))
                if from_email and to_email:
                    send_mail(
                        text['created_email_subject'],
                        text['created_email_body'].format(settings.DOMAIN_NAME, client.key),
                        from_email, [to_email]
                        )
                    log.info(text['created_log'].format(client.name, client.id))
            else:
                log.info(text['edited'].format(client.name, client.id))

            messages.add_message(request, messages.SUCCESS, text['created_success'])
            return HttpResponseRedirect(reverse('settings:clients_list'), {'messages': messages})
    else:
        client_form = ClientForm(instance=client)

    return TemplateResponse(request, template_name, {
        'client_form': client_form,
        'client_id': client_id if client_id else None,
        'client': client if client_id else None,
        'moduls': client.moduls() if client_id else None
    })


class ClientDeleteView(View):
    """
    Function which remove client from application. We use soft delete, so it's
    only marked as deleted.
    Client is removed from: - It's removed from all Groups
                            - All his moduls are removed on server.
                           #- Removed all moduls and clients if they appear in Events.
    """
    def get(self, request, *args, **kwargs):
        client_id = kwargs.get('client_id', None)
        client = get_object_or_404(Client, pk=client_id)
        client.deleted = True
        self.remove_tasks(client_id)
        # client.save()
        return HttpResponseRedirect(reverse('settings:clients_list'))

    def remove_tasks(self, client_id):
        """
        Support method, which remove all scheudeled tasks for some client on
        delete. In that way, when some client is removed, there is no activations
        or deactivations scheudeled for this client.
        """
        pass
        #moduls = Event.objects.filter()
        #start_task = AsyncResult()


class ModulList(View):
    template_name = "settings/moduls/moduls_list.html"

    def get(self, request, *args, **kwargs):
        context = {}
        context['moduls'] = all_online_moduls()
        names = []
        if context['moduls']:
            for name in context['moduls']:
                names.append(name.get('name', None))
            context['modul_names'] = names

        return TemplateResponse(
            request,
            self.template_name,
            context
        )


class ModulCreateView(FormView):
    form_class = ModulForm
    template_name = "settings/moduls/add_edit_modul.html"
    success_url = "/settings/moduls"

    def get(self, *args, **kwargs):
        return TemplateResponse(
            self.request,
            self.template_name, {
                'form': self.form_class
            })

    def post(self, request, *args, **kwargs):
        # Process view when the form gets POSTed
        pass
    form_class = GroupForm
    template_name = "settings/events/add_edit_event.html"
    success_url = "/settings/clients"


def send_data(page_url, data=None, action_type=None):
    """
    TODO
    """
    data = json.dumps(data)
    headers = {'Content-type': 'application/json'}
    request = requests.patch(url=page_url, data=data, headers=headers)
    return request.status_code


def activate_modul(request, status, client_id=None, pin_number=None):
    """
    Function is used to activate specific modul on specific client.
    As parameter we get modul pin number and id of parent client. Then we
    fill those values in prepared url string, to get activation url.
    If activation was successfully we get status code 200 and
    we make note into the logs, otherway we make notes about failed activation
    :param client_id: Id of the client, if modul have a parent
    :param pin_number: GPIO number which is used by modul
    :param status: Value which tell as if we would like to activate
                   or deactivate value (True=activate, False=deactivate)
    :type client_id: Integer
    :type pin_number: Integer
    :type status: Boolean
    """
    msg = {
        'activated': 'Activated modul with pin {0} on client {1}',
        'deactivated': '"Dectivated modul with pin {0} on client {1}',
        'failed': 'Failed to activate modul with pin{0} on client{1}'
    }
    data = {
        "is_activated": status
    }
    client = Client.objects.get(id=client_id)
    url = "http://{0}/api/gpio/update/{1}/".format(client.ip_address, pin_number)
    try:
        if send_data(url, data) == 200:
            if status == 'True':
                log.info(msg['activated'].format(pin_number, client.name))
            else:
                log.info(msg['deactivated'].format(pin_number, client.name))
    except:
        log.info(msg['failed'].format(pin_number, client.name))

    return HttpResponseRedirect(reverse('settings:clients_list'))


@login_required
def delete_modul(self, modul_id):
    """
    This method is in use to mark some modul as deleted. This means that
    this modul isn't visible anymore, but informations are still saved in
    the database

app/templates/settings/clients/add_edit_client.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% load widget_tweaks %}
{% block content %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                {% trans "Clients" %}
                {% if client_id %}
                    <small>{% trans " Edit client" %}</small>
                {% else %}
                    <small>{% trans " Add new" %}</small>
                {% endif %}
            </h1>

            <ol class="breadcrumb">
                <li class="active">
                    <i class="fa fa-dashboard"></i>
                    {% comment %}
                        <a href="{% url 'settings:client_statistics' client_id %}">
                    {% endcomment %}
                     {% if client_id %} 
                        {% if client.is_active %}                   
                                <button type="button" class="btn btn-xs btn-success">{% trans "Online" %}</button> 
                        {% else %}
                            <button type="button" class="btn btn-xs btn-default">{% trans "Offline" %}</button>
                        {% endif %}              
                     {% endif %}
                </li>
                {% if client %} 
                    <li class="system_buttons">
                        <a href="." class="btn btn-xs btn-info" role="button">{% trans "Reboot" %}</a>
                        <a href="." class="btn btn-xs btn-info" role="button">{% trans "Shutdown" %}</a>
                    </li>
                {% endif %}
            </ol>
            
        </div>
    </div>
    <!-- /.row -->
    <hr>
    <div class="main_container">
        <div class="first_container" />
            <form action= "
                        {% if client_id %}
                            {% url 'settings:edit_client' client_id %}
                        {% else %}
                            {% url 'settings:add_client'%}
                        {% endif %}
                          "
                        }

                     method="post"> 
                {% csrf_token %}
                {% for field in client_form %}
                    <div class="field_group" />
                        {{ field.label_tag }} </br>
                        {{ field|add_class:"form-control" }} </br>
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <div class="validation_error" >
                                    {{error}}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <small>{{field.help_text}}</small> </br>
                    </div>
                {% endfor %}
                
                <button type="button" class="btn btn-sm btn-default" data-toggle="modal" data-target=".bs-example-modal-sm">Test connection</button>
                <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                  <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                      <div class="alert alert-success" role="alert">
                        <center> SUCCESS </center>
                      </div>
                      <center> Connection was successful established. </center>
                      <br><br>
                    </div>
                  </div>
                </div>  

                <hr>      
                <button type="submit" class="btn btn-sm btn-primary">{% trans "Save" %}</button>
            </form>
        </div>
        <div class="second_container" />

            <fieldset>
                <legend>
                    <img class='icon' src="{% static 'images/maximize.png' %}" alt="title" /> 
                    {% trans "Basic settings" %}
                </legend>
                <div class="fieldset_content" data-state="close" >
                test
                </div>
            </fieldset>

            <fieldset>
                <legend>
                    <img class='icon' src="{% static 'images/maximize.png' %}" alt="title" /> 
                    {% trans "Moduls" %}
                </legend>
                <div class="fieldset_content" data-state="close" >
                    <div class="row" style="width:100%">
                        <div class="col-lg-12">
                            <div class="table-responsive">
                                {% if moduls %}
                                    <a href="{% url 'settings:add_modul' %}" class="btn btn-xs btn-info" role="button">
                                    {% trans "Add" %} </a>
                                    <button type="button" class="btn btn-xs btn-info">{% trans "Reset all" %}</button>
                                    <table class="table table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Pin number</th>
                                                <th>Group</th>
                                                <th>Input device</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for modul in moduls  %}
                                            <tr>
                                                <td>
    <a href="
            {% if modul.is_activated %}
                {% url 'settings:activate_modul' client_id=client_id pin_number=modul.pin_number status=False %}
            {% else %}
                 {% url 'settings:activate_modul' client_id=client_id pin_number=modul.pin_number status=True %}
            {% endif %}"
     class="
            activation_button 
            {% if modul.is_activated %}
                btn btn-xs btn-success
            {% else %}
                btn btn-xs btn-default
             {% endif %}"

    role="button"
    id ="{{modul.pin_number}}">
                                                    {{ modul.name }}
                                                </a>
                                                </td>
                                                <td>{{ modul.pin_number }}</td>
                                                <td>{{ modul.group }}</td>
                                                <td>{{ modul.is_input }}</td>
                                            </tr>
                                        {% endfor %}
                                {% else %}
                                   <p class="text-danger">
                                        No moduls available because connection is down
                                   </p>
                                {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

             </fieldset>

        </div>
    </div>

    <script src="{{ STATIC_URL }}js/common/common.js"></script> 
    
{% endblock %}

app/templates/settings/clients/client_statistics.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <!-- Page Heading -->
    <div class="row">
        test is statistics page for client <b> {{client_id}}</b>
    </div>
 
{% endblock %}

app/templates/settings/clients/clients.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                {% trans "Clients" %} 
            </h1>
            {% if messages %}
                {% for message in messages %}
                {% if message.tags == "success"%}
                    <div class="alert alert-info alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <i class="fa fa-info-circle"></i>  
                    <strong>Client</strong> has been <strong>successfully</strong> updated
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>


    <a href="{% url 'settings:add_client' %}" class="btn btn-sm btn-success"><span 
       class="glyphicon glyphicon-cog"></span> Add new</a>    
    <a href="#" class="btn btn-sm btn-info"><span class="glyphicon glyphicon-envelope"></span> Notification settings</a>


    <!-- /.row -->
    <hr>
        <div class="col-lg-14">
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>ID</th> 
                            <th>{% trans "Name" %}</th>
                            <th>{% trans "Description" %}</th>
                            <th>{% trans "IP address" %}</th>
                            <th>{% trans "Port" %}</th>
                            <th>{% trans "Created" %}</th>
                            <th>{% trans "Last active" %}</th> 

                        </tr>
                    </thead>
                    <tbody>
                    {% for client in clients%}                
                            {% if client.is_connected and client.last_active %}
                                <tr class="success">                
                               <td stye="width:100px"> <img class="myDiv" src="{% static 'images/ok_icon.png' %}" title='Connected'></td>
                            {% else %}
                                <tr>
                                <td style="width:35px"></td>
                            {% endif %}
                            <td>
                                <a href="{%url 'settings:edit_client' client.id%}" ><img src="{% static 'images/edit.png' %}" alt='Edit' /></a>

                                <a href="{%url 'settings:delete_client' client.id%}" ><img src="{% static 'images/remove.png' %}" alt='Remove' title='Remove' /> </a>

                                <a href="{%url 'settings:edit_client_notification' client.id%}" >
                                <img src="{% static 'images/mute.png' %}" alt="Notification settings" title="Notification settings" /></a>
                            </td>
                            <td>{{client.id}}</td>
                            <td>{{client.name}}</td>
                            <td>{{client.description}}</td>
                            <td>{{client.ip_address}}</td>
                            <td>{{client.port}}</td>
                            <td>{{client.created}}</td>
                            {% ifequal client.last_active None %}
                                <td> - </td>
                            {% else %}
                                <td>{{client.last_active}}</td>
                            {% endifequal %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        
            <br>

            <nav>
              <ul class="pagination">
                <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">2 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">3 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">4 <span class="sr-only">(current)</span></a></li>
                <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
              </ul>
            </nav>
        </div>
    <hr>
    <script src="{{ STATIC_URL }}js/pages/clients.js"></script>  
{% endblock %}

app/templates/settings/clients/edit_client_notification.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <!-- Page Heading -->
    <div class="row">
        test edit notification for client <b> {{client_id}}</b>
    </div>
 
{% endblock %}