app/api/urls.py
from django.conf.urls import patterns, include, url

from rest_framework.urlpatterns import format_suffix_patterns

from . import viewsets

urlpatterns = patterns('',
   url(r'^$', viewsets.api_root),
   url(r'^clients/$', viewsets.ClientViewSet.as_view({'get': 'list'}), name='client-list'),
   url(r'^groups/$', viewsets.GroupViewSet.as_view({'get': 'list'}), name='group-list')
)

urlpatterns = format_suffix_patterns(urlpatterns)

app/dashboard/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = patterns('',
  url(r'^$', views.dashboard, name="dashboard"),
  url(r'^weather/$', views.weather_full, name='weather_full'),
    )

app/entertainment/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
  url(r'^music/$', views.music.as_view(), name='music'),
    )

app/project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AdminPasswordChangeForm
from django.conf.urls.i18n import i18n_patterns

import logging


log = logging.getLogger(__name__)

urlpatterns = i18n_patterns('',

  url(r'^admin/', include(admin.site.urls)),
  url(r'^i18n/', include('django.conf.urls.i18n')),
  

  url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
  url(r'^settings/', include('setting.urls', namespace='settings')),
  url(r'^api/', include('api.urls', namespace="api")),
  url(r'^entertainment/', include('entertainment.urls', namespace="entertainment")),
  
  url(r'^$', auth_views.login, {'template_name': 'project/index.html'}, name="login"),
  url(r'password/reset/$', auth_views.password_reset, 
        {'post_reset_redirect' : '/password/reset/done/',
        'template_name': 'registration/password_reset_form.html'},
        name="password_reset"),
  url(r'^password/reset/done/$', auth_views.password_reset_done, name='password_reset_done' ),
  url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect' : '/password/reset/complete/'}, name='password_reset_confirm'),
  url(r'^password/reset/complete/$', auth_views.password_reset_complete),

  )

app/setting/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',

       url(r'^logout/$', views.user_logout,
           name='user_logout'),

       url(r'^general_settings/$', views.GeneralSettingsView.as_view(),
           name='general_settings'),

       url(r'^users/$', views.users_list, name='users_list'),
       #url(r'^users/add/$', views.add_edit_user,
           #name='add_user'),
       url(r'^users/edit/(?P<pk>[0-9]+)/$',
           views.EditUserView.as_view(), name='edit_user'),

       url(r'^groups/$', views.GroupListView.as_view(),
           name='groups_list'),
       url(r'^groups/add/$', views.AddGroupView.as_view(),
           name='add_group'),
       url(r'^groups/edit/(?P<pk>[0-9]+)/$',
           views.EditGroupView.as_view(), name='edit_group'),

       url(r'^moduls/$', views.ModulList.as_view(),
           name='moduls_list'),
       url(r'^moduls/add/$',
           views.ModulCreateView.as_view(), name='add_modul'),
       url(r'^moduls/delete/(?P<modul_id>[0-9]+)/$',
           views.delete_modul, name='delete_modul'),

       url(r'^clients/$', views.ClientListView.as_view(),
           name='clients_list'),
       url(r'^clients/add/$', views.add_edit_client,
           name='add_client'),
       url(r'^clients/edit/(?P<client_id>[0-9]+)/$',
           views.add_edit_client, name='edit_client'),
       url(r'^clients/delete/(?P<client_id>[0-9]+)/$',
           views.ClientDeleteView.as_view(), name='delete_client'),
       url(r'^clients/notification_settings/(?P<client_id>[0-9]+)/$',
           views.edit_client_notification, name='edit_client_notification'),

       url(r'^moduls/activate/(?P<client_id>[0-9]+)/(?P<pin_number>[0-9]+)/(?P<status>[A-Za-z]+)/$',
           views.activate_modul, name='activate_modul'),

       url(r'^events/add/$', views.AddEventView.as_view(),
           name='add_event'),
       url(r'^events/edit/(?P<pk>[0-9]+)/$',
           views.EditEventView.as_view(), name='edit_event'),
       )

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Bostjan Novak">
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
        <title>StrawberryPie- Development version</title>
        {% load staticfiles %}

        <link href="{{ STATIC_URL }}public/bundle.css" rel="stylesheet">
        <script src="{{ STATIC_URL }}bower_components/jquery/dist/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}bower_components/font-awesome/css/font-awesome.min.css"/>
    </head>
    
    <body onload="updateClock(); setInterval('updateClock()', 1000 )">
        <div id="wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                {% include "header_menu.html" %}
                {% include "sidebar_menu.html" %}
            </nav>
            <div id="page-wrapper">
                <div class="container-fluid"> 

                    {% block content %}
                    {% endblock %}              
                </div>
            </div>
        </div>

        

        <script src="{{ STATIC_URL }}js/pages/utils.js"></script>

        <script type="text/javascript">
            var paths={
                'fieldset_open': "{% static 'images/maximize.png' %}",
                'fieldset_close': "{% static 'images/minimize.png' %}" 
            }
        </script>
    </body>
</html>

app/templates/header_menu.html
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" 

                   
                >
                </a>
            </div>
            <!-- Top Menu Items -->
               <ul class="nav navbar-right top-nav">
                <li class="dropdown" id="mail_background">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i id="mail" class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                            
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>Novakus</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>John Smith</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>

                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown" id="alarm_background">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i id="alarm" class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'settings:edit_user' user.id %}"><i class="fa fa-fw fa-user"></i>My profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i>Notifications</a>
                        </li>
                        {% comment %}
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>                                                
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        {% endcomment %}
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'settings:user_logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul> 
            

app/templates/sidebar_menu.html
{% load i18n %}

<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->

<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li class="active">
            <a href="{% url 'dashboard:dashboard' %}"><i class="fa fa-fw fa-dashboard"></i> {% trans "Dashboard" %}</a>
        </li>
        {% comment %}
            <li>
                <a href="bootstrap-grid.html"><i class="fa fa-fw fa-wrench"></i> Speach</a>
            </li>
        {% endcomment %}
        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v"></i> Test page <i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="demo" class="collapse">
                <li>
                    <a href="{% url 'entertainment:music' %}">Test page</a>
                </li>
                {% comment %}
                <li>
                        <a href="#">Stream video</a>
                </li>
                {% endcomment %}
            </ul>
        </li>
        <li>
            <a href="{% url 'settings:add_event' %}" data-toggle="collapse" data-target="#actions"><i   class="fa fa-fw fa-table"></i> 
               {% trans "Events" %} 
            </a>
        </li>

        <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#settings"><i class="fa fa-fw fa-wrench"></i> {% trans "Settings" %}<i class="fa fa-fw fa-caret-down"></i></a>
            <ul id="settings" class="collapse">
                <li>
                    <a href="{% url 'settings:general_settings' %}">{% trans "General settings" %}</a>
                </li>
                <li>
                    <a href="{% url 'settings:groups_list' %}">{% trans "Groups" %}</a>
                </li>
                <li>
                    <a href="{% url 'settings:clients_list' %}">{% trans "Clients" %}</a>
                </li>
                <li>
                    <a href="{% url 'settings:moduls_list' %}">{% trans "All moduls" %}</a>
                </li>
                <li>
                    <a href="{% url 'settings:users_list'%}">{% trans "Users" %}</a>
                </li>
            </ul>
        </li>
    </ul>
</div>